Clase/urls.py
from django.urls import path
from Clase.views import (
    index, estudiante_list,
    estudiante_create,
    profesor_create,
    profesor_list,
    principal_profesores,
    principal_cursos,
    curso_create,
    curso_list,
    CursoDetail,
    CursoDelete,
    CursoUpdate,
    EstudianteDelete,
    ProfesorDelete,
    ProfesorUpdate,
    ProfesorCreate,
    about)

app_name = "Clase"

urlpatterns = [
    path("", index, name="index"),
    path("Clase/list", estudiante_list,name="estudiante_list" ),
    path("Clase/create", estudiante_create,name="estudiante_create" ),
    path("principal_profesores", principal_profesores,name="principal_profesores" ),
    path("profesor_list", profesor_list,name="profesor_list" ),
    path("principal_cursos", principal_cursos,name="principal_cursos" ),
    path("curso_create", curso_create,name="curso_create" ),
    path("curso_list", curso_list,name="curso_list" ),
    path("curso/detail/<int:pk>", CursoDetail.as_view(), name="curso_detail"),
    path("curso/delete/<int:pk>", CursoDelete.as_view(), name="curso_delete"),
    path("curso/update/<int:pk>", CursoUpdate.as_view(), name="curso_update"),
    path("estudiante/delete/<int:pk>", EstudianteDelete.as_view(), name="estudiante_delete"),
    path("profesor/delete/<int:pk>", ProfesorDelete.as_view(), name="profesor_delete"),
    path("profesor/update/<int:pk>", ProfesorUpdate.as_view(), name="profesor_update"),
    path("profesor/create", ProfesorCreate.as_view(), name="profesor_create"),
    path("Clase/about",about,name="about")
]

Escuela/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("Clase/", include("Clase.urls")),
]

core/urls.py
from django.urls import path
from . import views
from core.views import register
from core.views import CustomLoginView
from django.contrib.auth.views import LogoutView

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/",CustomLoginView.as_view(),name="login"),
    path("logout/",LogoutView.as_view(template_name="core/logout.html"),name="logout"),
    path("register/",register, name="register")
]

Clase/models.py
from django.db import models
from django.utils import timezone

class Curso(models.Model):
    nombre = models.CharField(max_length=255, unique=True)
    detalle = models.CharField(max_length=800,null=True, blank=True)
    
    def __str__(self) -> str:   
        return self.nombre
    
    class Meta:
        verbose_name = "Curso"
        verbose_name_plural = "Cursos"
    
class Estudiante(models.Model):
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    nacimiento = models.DateField(null=True, blank=True)
    materia = models.ForeignKey(Curso, on_delete=models.CASCADE,null=True)
    inscripcion = models.DateTimeField(default=timezone.now)
    
    
    def __str__(self) -> str:
        return f"{self.nombre},{self.apellido},{self.nacimiento}"
    
    class Meta:
        verbose_name = "Estudiante"
        verbose_name_plural = "Estudiantes"
        
        
class Profesor(models.Model):
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    materia = models.ForeignKey(Curso, on_delete=models.SET_NULL,null=True)
    
    def __str__(self) -> str:
        return f"{self.nombre},{self.apellido}"
    
    class Meta:
        verbose_name = "Profesor"
        verbose_name_plural = "Profesores"
        

Clase/forms.py
from django import forms

from . import models

class EstudianteForm(forms.ModelForm):
    class Meta:
        model = models.Estudiante
        fields = ["nombre","apellido","nacimiento","materia"]
        
class ProfesorForm(forms.ModelForm):
    class Meta:
        model = models.Profesor
        fields = ["nombre","apellido","materia"]
        
class CursoForm(forms.ModelForm):
    class Meta:
        model = models.Curso
        fields = ["nombre","detalle"]
        widgets = {
            'detalle': forms.Textarea(attrs={'rows': 10, 'cols': 60}),  # Ajusta rows y cols según sea necesario
        }

Clase/views.py
from django.shortcuts import render, redirect
from .models import Estudiante,Profesor,Curso
from Clase.forms import EstudianteForm,ProfesorForm,CursoForm
from django.views.generic import CreateView,ListView,DetailView,DeleteView,UpdateView
from django.urls import reverse_lazy
# Create your views here.

def index(request):
    return render(request,"Clase/index.html")

def estudiante_list(request):
    busqueda = request.GET.get("busqueda",None)
    if busqueda:
        print(busqueda)
        consulta = Estudiante.objects.filter(nombre__icontains=busqueda)
    else: 
        consulta = Estudiante.objects.all()
    contexto = {"estudiantes": consulta}
    return render(request,"Clase/estudiante_list.html", contexto)

def estudiante_create(request):
    if request.method == "POST":
        form = EstudianteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Clase:index")
        
    else: #GET
        form = EstudianteForm()
    return render(request, "Clase/estudiante_create.html",{"form":form})

def profesor_create(request):
    if request.method == "POST":
        form = ProfesorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Clase:principal_profesores")
        
    else: #GET
        form = ProfesorForm()
    return render(request, "Clase/profesor_create.html",{"form":form})

def profesor_list(request):
    busqueda = request.GET.get("busqueda",None)
    if busqueda:
        print(busqueda)
        consulta = Profesor.objects.filter(nombre__icontains=busqueda)
    else:
       consulta = Profesor.objects.all()
    contexto = {"profesores": consulta}
    return render(request,"Clase/profesor_list.html", contexto)

def principal_profesores(request):
    return render(request,"Clase/principal_profesores.html")

def principal_cursos(request):
    return render(request,"Clase/principal_cursos.html")

def curso_create(request):
    if request.method == "POST":
        form = CursoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Clase:principal_cursos")
        
    else: #GET
        form = CursoForm()
    return render(request, "Clase/curso_create.html",{"form":form})


def curso_list(request):
    busqueda = request.GET.get("busqueda",None)
    if busqueda:
        print(busqueda)
        consulta = Curso.objects.filter(nombre__icontains=busqueda)
    else:
        consulta = Curso.objects.all()
    contexto = {"cursos": consulta}
    return render(request,"Clase/curso_list.html", contexto)


class CursoDetail(DetailView):
    model = Curso


class CursoDelete(DeleteView):
    model = Curso
    success_url = reverse_lazy("Clase:curso_list")
    
    
class CursoUpdate(UpdateView):
    model = Curso
    form_class = CursoForm
    success_url = reverse_lazy("Clase:curso_list")
    
class EstudianteDelete(DeleteView):
    model = Estudiante
    success_url = reverse_lazy("Clase:estudiante_list")
    
class ProfesorDelete(DeleteView):
    model = Profesor
    success_url = reverse_lazy("Clase:profesor_list")
    
class ProfesorUpdate(UpdateView):
    model = Profesor
    form_class = ProfesorForm
    success_url = reverse_lazy("Clase:profesor_list")
    
class ProfesorCreate(CreateView):
    model = Profesor
    form_class = ProfesorForm
    success_url = reverse_lazy("Clase:profesor_list")
    
def about(request):
    return render(request,"Clase/about.html")

Clase/templates/Clase/about.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
    

<style>
    body {
        font-family: Arial, sans-serif;
        line-height: 1.6;
        margin: 0;
        padding: 0;
        background-color: #f4f4f4;
        color: #333;
    }
    .container {
        max-width: 800px;
        margin: auto;
        padding: 20px;
        text-align: center;
    }
    img {
        border-radius: 50%;
        width: 440px;
        height: 440px; /* Establecer la altura igual al ancho */
        margin-bottom: 20px;
    }
    h3 {
        color: #007bff;
    }
</style>
</head>
<body>
<div class="container">
    <img src="{% static 'core/img/Fotocamisa.jpg' %}" alt="Foto de Santiago Pajon">
    <h3>Acerca de Mí</h3>
    <h2>Santiago Pajon</h2>
    <p>Hola, soy Santiago Pajon. Tengo 20 años y actualmente trabajo en la empresa Aluar - División Elaborados desde hace dos años. Estoy incursionando en el mundo de la programación y he adquirido conocimientos en Python y el framework Django gracias al curso en CoderHouse. ¡Gracias por visitar mi página!</p>
</div>
</body>
{% endblock content %}

Clase/templates/Clase/curso_confirm_delete.html
{% extends 'core/base.html' %}

{% block title %}
    Cursos | Curso
{% endblock title %}

{% block body_title %} 
    Cursos | Curso - Eliminar
{% endblock body_title %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <p class="fs-5 fst-italic">Desea eliminar "{{ object.nombre }}"?</p>
            <form action="" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Confirmar</button>
            </form>
            <a href="{% url 'Clase:curso_list' %}" class="btn btn-secondary mt-2">Volver al inicio de producto</a>
        </div>
    </div>
</div>

{% endblock content %}

Clase/templates/Clase/curso_create.html
{% extends 'core/base.html' %}

{% block title %}
    Cursos | Creacion
{% endblock title %}

{% block content %}
    <center>
    <h1>Creacion de Curso</h1>
    </center>
    <center>
        <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-6">
                <form class="p-3 border rounded-lg bg-light" action="" method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button class="btn btn-primary mt-3" type="submit">Guardar</button>
                </form>
              </div>
            </div>
          </div>
          
    </center>
{% endblock content %}

Clase/templates/Clase/curso_detail.html
{% extends 'core/base.html' %}

{% block title %}
    Curso | Detalle del curso:
{% endblock title %}

{% block body_title %}
    Curso | Detalle del curso:
{% endblock body_title %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <ul class="list-group">
                <li class="list-group-item"><strong>Nombre:</strong> {{ object.nombre }}</li>
                <li class="list-group-item"><strong>Detalle:</strong> {{ object.detalle }}</li>
            </ul>
            <div class="mt-3">
                <a href="{% url 'Clase:curso_list' %}" class="btn btn-primary">Volver</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

Clase/templates/Clase/curso_list.html
{% extends 'core/base.html' %}

{% block title %}
    Lista de Cursos
{% endblock title %}

{% block content %}
    
<div class="container">
  <div class="row">
      <div class="col text-center">
          <h1>Listado de Cursos</h1>
      </div>
  </div>
  <div class="row justify-content-center">
      <div class="col-md-6">
          {% for curso in cursos %}
              <div class="card mb-3">
                  <div class="card-body">
                      <h3 class="card-title">{{ curso.nombre }}</h3>
                      <a href="{% url 'Clase:curso_detail' curso.id %}" class="btn btn-primary">Detalle</a>
                      {% if user.is_staff %}
                        <a href="{% url 'Clase:curso_delete' curso.id %}" class="btn btn-primary">Eliminar</a>
                      {% endif %}
                  </div>
              </div>
          {% endfor %}
      </div>
  </div>
</div>

      </div>
    </div>
    
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <form action="{% url 'Clase:curso_list' %}" method="get">
          <div class="input-group mb-3">
            <input type="text" class="form-control" name="busqueda" placeholder="Buscar...">
            <div class="input-group-append">
              <button class="btn btn-outline-secondary" type="submit">Buscar</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  
{% endblock content %}

Clase/templates/Clase/estudiante_confirm_delete.html
{% extends 'core/base.html' %}

{% block title %}
    Estudiantes | Estudiante
{% endblock title %}

{% block body_title %} 
    Estudiantes | Estudiante - Eliminar
{% endblock body_title %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <p class="fs-5 fst-italic">Desea eliminar "{{ object.nombre }}"?</p>
            <form action="" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Confirmar</button>
            </form>
            <a href="{% url 'Clase:estudiante_list' %}" class="btn btn-secondary mt-2">Volver al inicio de producto</a>
        </div>
    </div>
</div>

{% endblock content %}

Clase/templates/Clase/estudiante_create.html
{% extends 'core/base.html' %}

{% block title %}
    Estudiantes | Creacion
{% endblock title %}

{% block content %}
    <center>
    <h1>Creacion de Estudiantes</h1>
    </center>
    <center>
        <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-6">
                <form class="p-3 border rounded-lg bg-light" action="" method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button class="btn btn-primary mt-3" type="submit">Guardar</button>
                </form>
              </div>
            </div>
          </div>
          
    </center>
{% endblock content %}

Clase/templates/Clase/estudiante_list.html
{% extends 'core/base.html' %}

{% block title %}
    Lista de estudiantes
{% endblock title %}

{% block content %}

<center>
  <h1>Listado de estudiantes</h1>
</center>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      {% for estudiante in estudiantes %}
      <div class="card mb-3">
        <div class="card-body">
          <h3 class="card-title">{{ estudiante.nombre }} {{ estudiante.apellido }}</h3>
          {% if estudiante.nacimiento %}
          <p class="card-text">Nacimiento: {{ estudiante.nacimiento }}</p>    
          {% else %}
          <p class="card-text">Nacimiento: No hay registro</p>
          {% endif %}
          <p class="card-text">Materia: {{ estudiante.materia }}</p>
          <p class="card-text">Inscripción: {{ estudiante.inscripcion }}</p>
          {% if user.is_staff %}
          <a href="{% url 'Clase:estudiante_delete' estudiante.id %}" class="btn btn-primary">Eliminar</a>
          {% endif %}
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  
  <div class="row justify-content-center">
    <div class="col-md-6">
      <form action="{% url 'Clase:estudiante_list' %}" method="get">
        <div class="input-group mb-3">
          <input type="text" class="form-control" name="busqueda" placeholder="Buscar...">
          <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="submit">Buscar</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

  
{% endblock content %}

Clase/templates/Clase/index.html
{% extends 'core/base.html' %}
{% block title %}
    Estudiantes
{% endblock title %}

{% block content %}
<center>    
<h1>Estudiantes</h1>
</center>
<center>
<div>
    <ul style="list-style-type: none; padding: 0;">
        <li style="display: inline; margin-right: 10px;">
            <a href="{% url 'Clase:estudiante_list' %}" style="text-decoration: none; color: #007bff; font-family: Arial, sans-serif; font-weight: bold;">Lista de estudiantes</a>
        </li>
        {% if user.is_staff %}
            <li style="display: inline;">
                <a class="btn.btn-primary" href="{% url 'Clase:estudiante_create' %}" style="text-decoration: none; color: #007bff; font-family: Arial, sans-serif; font-weight: bold;">Crear estudiante</a>
            </li>
        {% endif %}
    </ul>
</div>
</center>
{% endblock content %}

Clase/templates/Clase/principal_cursos.html
{% extends 'core/base.html' %}
{% block title %}
    Cursos
{% endblock title %}

{% block content %}
<center>
    <h1>Cursos</h1>
</center> 
<center>
<div>
    <ul style="list-style-type: none; padding: 0;">
        <li style="display: inline; margin-right: 10px;">
            <a href="{% url 'Clase:curso_list' %}" style="text-decoration: none; color: #007bff; font-family: Arial, sans-serif; font-weight: bold;">Lista de Cursos</a>
        </li>
        {% if user.is_staff %}
            <li style="display: inline;">
                <a href="{% url 'Clase:curso_create' %}" style="text-decoration: none; color: #007bff; font-family: Arial, sans-serif; font-weight: bold;">Crear Curso</a>
            </li>
        {% endif %}
    </ul>
</div>
</center>
{% endblock content %}

Clase/templates/Clase/principal_profesores.html
{% extends 'core/base.html' %}
{% block title %}
    Profesores
{% endblock title %}

{% block content %}
<center>
<h1>Profesores</h1>
</center>
<center>
<div>
    <ul style="list-style-type: none; padding: 0;">
        <li style="display: inline; margin-right: 10px;">
            <a href="{% url 'Clase:profesor_list' %}" style="text-decoration: none; color: #007bff; font-family: Arial, sans-serif; font-weight: bold;">Lista de Profesores</a>
        </li>
        {% if user.is_staff %}
            <li style="display: inline;">
                <a href="{% url 'Clase:profesor_create' %}" style="text-decoration: none; color: #007bff; font-family: Arial, sans-serif; font-weight: bold;">Crear Profesor</a>
            </li>
        {% endif %}
    </ul>
</div>
</center>
{% endblock content %}

Clase/templates/Clase/profesor_confirm_delete.html
{% extends 'core/base.html' %}

{% block title %}
    Profesores | Profesor
{% endblock title %}

{% block body_title %} 
    Profesores | Profesor - Eliminar
{% endblock body_title %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <p class="fs-5 fst-italic">Desea eliminar "{{ object.nombre }}"?</p>
            <form action="" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Confirmar</button>
            </form>
            <a href="{% url 'Clase:profesor_list' %}" class="btn btn-secondary mt-2">Volver al inicio de producto</a>
        </div>
    </div>
</div>

{% endblock content %}

Clase/templates/Clase/profesor_create.html
{% extends 'core/base.html' %}

{% block title %}
    Profesor | Creacion
{% endblock title %}

{% block content %}
    <center>
    <h1>Creacion de Profesor</h1>
    </center>
    <center>
        <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-6">
                <form class="p-3 border rounded-lg bg-light" action="" method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button class="btn btn-primary mt-3" type="submit">Guardar</button>
                </form>
              </div>
            </div>
          </div>
          
    </center>
{% endblock content %}

Clase/templates/Clase/profesor_form.html
{% extends 'core/base.html' %}

{% block title %}
    Profesor | Creacion
{% endblock title %}
  {% if form.instance.pk %}
    Profesor |  - Edicion
  {% else %}
    Profesor |  - Creacion  
  {% endif %}
{% block content %}
    <center>
    <h1>Creacion de Profesor</h1>
    </center>
    <center>
        <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-6">
                <form class="p-3 border rounded-lg bg-light" action="" method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button class="btn btn-primary mt-3" type="submit">Guardar</button>
                </form>
              </div>
            </div>
          </div>
          
    </center>
{% endblock content %}