Clase/urls.py
from django.urls import path
from Clase.views import (
    index, estudiante_list,
    estudiante_create,
    profesor_create,
    profesor_list,
    principal_profesores,
    principal_cursos,
    curso_create,
    curso_list,
    CursoDetail,
    CursoDelete,
    CursoUpdate,
    EstudianteDelete,
    ProfesorDelete,
    ProfesorUpdate,
    ProfesorCreate,
    about)

app_name = "Clase"

urlpatterns = [
    path("", index, name="index"),
    path("Clase/list", estudiante_list,name="estudiante_list" ),
    path("Clase/create", estudiante_create,name="estudiante_create" ),
    path("principal_profesores", principal_profesores,name="principal_profesores" ),
    path("profesor_list", profesor_list,name="profesor_list" ),
    path("principal_cursos", principal_cursos,name="principal_cursos" ),
    path("curso_create", curso_create,name="curso_create" ),
    path("curso_list", curso_list,name="curso_list" ),
    path("curso/detail/<int:pk>", CursoDetail.as_view(), name="curso_detail"),
    path("curso/delete/<int:pk>", CursoDelete.as_view(), name="curso_delete"),
    path("curso/update/<int:pk>", CursoUpdate.as_view(), name="curso_update"),
    path("estudiante/delete/<int:pk>", EstudianteDelete.as_view(), name="estudiante_delete"),
    path("profesor/delete/<int:pk>", ProfesorDelete.as_view(), name="profesor_delete"),
    path("profesor/update/<int:pk>", ProfesorUpdate.as_view(), name="profesor_update"),
    path("profesor/create", ProfesorCreate.as_view(), name="profesor_create"),
    path("Clase/about",about,name="about")
]

Escuela/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("Clase/", include("Clase.urls")),
]

core/urls.py
from django.urls import path
from . import views
from core.views import register
from core.views import CustomLoginView
from django.contrib.auth.views import LogoutView

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/",CustomLoginView.as_view(),name="login"),
    path("logout/",LogoutView.as_view(template_name="core/logout.html"),name="logout"),
    path("register/",register, name="register")
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username","password"]
        
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username","password1","password2"]

core/views.py
from django.shortcuts import render
from core.forms import CustomAuthenticationForm,CustomUserCreationForm
from django.contrib.auth.views import LoginView 

# Create your views here.

def index(request):
    return render(request,"core/index.html")

class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "core/login.html"
    
def register(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            form.save()
            return render(request,"core/index.html",{"mensaje":f"Usuario {username} creado"})
        
    else:
        form = CustomUserCreationForm()
    return render(request,"core/register.html",{"form":form})

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %} " rel="stylesheet" />
    </head>
    <body style="display: flex; flex-direction: column; min-height: 100vh;">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'core:index' %}">Coder Casa</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Inicio</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'Clase:principal_cursos' %}">Curso</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Clase:index' %}">Estudiante</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Clase:principal_profesores'%}">Profesor</a></li>
                        <li class="nav-item"><a class="nav-link">{{user.username}}</a></li>
                        
                        <li class="nav-item">
                            <form action="{% url 'core:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-dark ">Logout</button>
                            </form>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Clase:about' %}">About</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'core:login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'core:register' %}">Registrarse</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}
        {% endblock content %}
        <!-- Footer-->
        <footer style="margin-top: auto; background-color: #333; color: #fff; text-align: center; padding: 15px;" class="py-5 bg-dark">
            <div class="container px-4 px-lg-5"><p style="margin: 0;" class="m-0 text-center text-white">Copyright &copy; CoderCasa 2024</p></div>
        </footer>
       
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'core/js/scripts.js' %}"></script>
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
    CoderCasa
{% endblock title %}
{% block content %}
<!-- Responsive navbar-->

<!-- Page Content-->
<div class="container px-4 px-lg-5">
    <!-- Heading Row-->
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" 
            src="{% static 'core/img/imagen.png' %}" alt="..." /></div>
        <div class="col-lg-5">
            <h1 class="font-weight-light">CoderCasa</h1>
            <p>¡Bienvenido a nuestra plataforma de aprendizaje en línea! Somos una empresa dedicada a ofrecerte la oportunidad de ampliar tus habilidades en programación desde la comodidad de tu hogar. Nuestros cursos están diseñados para cubrir una amplia gama de temas, desde los fundamentos de la programación hasta tecnologías avanzadas y tendencias emergentes en el mundo del desarrollo de software. Con instructores expertos y contenido de calidad, te proporcionamos las herramientas necesarias para que puedas avanzar en tu carrera profesional o explorar tu pasión por la programación. </p>
            
        </div>
    </div>
    <!-- Call to Action-->
    <div class="card text-white bg-secondary my-5 py-4 text-center">
        <div class="card-body"><p class="text-white m-0">Tambien apoyamos a nuestos amigos de CoderHouse, aqui abajo algunos cursos...</p></div>
    </div>
    <!-- Content Row-->
    <div class="row gx-4 gx-lg-5">
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">Curso Python</h2>
                    <p class="card-text">En este curso, aprenderás las bases de programación en uno de los lenguajes más populares en la actualidad. Desde los fundamentos hasta la creación de aplicaciones web estilo blog usando Python en el Django Framework, cubrirás módulos, sintaxis y reglas, incluyendo Class-Based-View, login-register-accounts, CRUD y modelforms.</p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href="https://www.coderhouse.com/ar/online/python" target="_blank">Mas info</a></div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">Curso SAP</h2>
                    <p class="card-text">Este curso enseña los conceptos básicos de navegación y usabilidad en SAP, incluyendo finanzas, control de gestión, manejo de materiales, recursos humanos y ventas. Su objetivo es proporcionar una comprensión clara de los procesos empresariales y la estructura organizativa en la plataforma.</p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href="https://www.coderhouse.com/ar/online/sap" target="_blank">Mas info</a></div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">Curso SQL</h2>
                    <p class="card-text">
                        En este curso, aprenderás fundamentos de bases de datos relacionales y cómo crearlas desde cero. Dominarás consultas SQL avanzadas para generar informes y tomar decisiones. Estarás listo para analizar datos en cualquier modelo de negocio.</p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href="https://www.coderhouse.com/ar/online/sql" target="_blank">Mas info</a></div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}
    CoderCasa
{% endblock title %}

{% block body_title %}
    Login
{% endblock body_title %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title text-center mb-4">Iniciar Sesión</h3>
                    <form method="post" class="login-form">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Usuario:</label>
                            {{ form.username }}
                        </div>
                        <div class="mb-3">
                            <label for="id_password" class="form-label">Contraseña:</label>
                            {{ form.password }}
                        </div>
                        <input type="hidden" name="next" value="{% url 'core:index' %}">
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
                            <a href="{% url 'core:index' %}" class="btn btn-secondary">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

core/templates/core/logout.html
{% extends 'core/base.html' %}

{% block title %}
    CoderCasa
{% endblock title %}

{% block body_title %}
    Logout
{% endblock body_title %}

{% block content %}
<div class="container mt-5">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>¡Cierre de sesión exitoso!</strong> Has cerrado sesión correctamente. ¡Esperamos verte pronto de nuevo!
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
</div>

{% endblock content %}

core/templates/core/register.html
{% extends 'core/base.html' %}

{% block title %}
    Register
{% endblock title %}

{% block body_title %}
    Registro de Usuario
{% endblock body_title %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" class="needs-validation" novalidate>
                        {% csrf_token %}
                        <table class="table">
                            {{ form.as_table }}
                        </table>
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary">Registrarse</button>
                            <a href="{% url 'core:index' %}" class="btn btn-secondary">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}